# Generated by Django 4.0.3 on 2022-09-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
